#docker compose for agora multisites
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    volumes:
      - /home/ubuntu/dev/agoraMultiSites/db_data:/var/lib/mysql
      - /home/ubuntu/dev/agoraMultiSites/db_backup_working:/backup
    networks:
      - agora-network


  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_ALLOW_MULTISITE: 1
    entrypoint: /usr/local/bin/entrypoint.sh
    volumes:
      - /home/ubuntu/dev/agoraMultiSites/wordpress_entrypoint.sh:/usr/local/bin/entrypoint.sh
      - /home/ubuntu/dev/agoraMultiSites/wordpress_files:/var/www/html
      - /home/ubuntu/dev/agoraMultiSites/apache2_sites_available:/etc/apache2/sites-available
      - /home/ubuntu/dev/agoraMultiSites/letsencrypt:/etc/letsencrypt
      - /home/ubuntu/dev/agoraMultiSites/wordpress_backup:/backup
    ports:
      - "80:80"
      - "443:443"
    networks:
      - agora-network

networks:
  agora-network:

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/dev/agoraMultiSites/mysql_data
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
       type: none
       device: /home/ubuntu/dev/agoraMultiSites/wordpress_files
       o: bind


