FROM httpd:latest

COPY ./vhosts /usr/local/apache2/conf/sites-available
COPY ./certs /etc/letsencrypt
COPY ./vhosts/httpd.conf /usr/local/apache2/conf/httpd.conf

RUN mkdir /usr/local/apache2/conf/sites-enabled # Create sites-enabled directory

RUN ln -s /usr/local/apache2/conf/sites-available/atlas22.ai.conf /usr/local/apache2/conf/sites-enabled/atlas22.ai.conf && \
    ln -s /usr/local/apache2/conf/sites-available/hyperqube.net.conf /usr/local/apache2/conf/sites-enabled/hyperqube.net.conf

RUN echo "Include /usr/local/apache2/conf/sites-enabled/*.conf" >> /usr/local/apache2/conf/httpd.conf


# If using an entrypoint script, uncomment the lines below:
# COPY entrypoint.sh /usr/local/bin/
# ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
